version: '3.8'

services: 
    todo-app:
        build: ./
        command: ./wait-for-postgres.sh db ./todo-app
        ports: 
            - 8000:8000
        depends_on: 
            - db
        environment: 
            - DB_PASSWORD=1234

    db:
        restart: always
        image: postgres:latest
        volumes: 
            - ./.database/postgres/data:/var/lib/postgresql/data
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1234
            - POSTGRES_DB=postgres
        ports: 
            - 5436:5432